name: macOS

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: CMake Build
        run: |
          mkdir build && cd build
          cmake ..
          make
