name: Windows

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: CMake Build
        shell: powershell
        run: |
          $env:path=$env:path.Replace("C:\Program Files\Git", "HIDE_GIT")
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
